#if defined(ARDUINO_GENERIC_F401CBUX) || defined(ARDUINO_GENERIC_F401CBYX) ||\
    defined(ARDUINO_GENERIC_F401CCFX) || defined(ARDUINO_GENERIC_F401CCUX) ||\
    defined(ARDUINO_GENERIC_F401CCYX) || defined(ARDUINO_GENERIC_F401CDUX) ||\
    defined(ARDUINO_GENERIC_F401CDYX) || defined(ARDUINO_GENERIC_F401CEUX) ||\
    defined(ARDUINO_GENERIC_F401CEYX)

#endif /* ARDUINO_GENERIC_* */
