#!/bin/bash

BUILD_PATH="$1"
BUILD_SOURCE_PATH="$2"
BOARD_PLATFORM_PATH="$3"

# Create sketch dir if not exists
if [ ! -f "$BUILD_PATH/sketch" ]; then
  mkdir -p "$BUILD_PATH/sketch"
fi

# Create empty build.opt if build_opt.h does not exists in the original sketch dir
# Then add or append -fmacro-prefix-map option to change __FILE__ absolute path of
# the board platform folder to a relative path by using '.'.
# (i.e. the folder containing boards.txt)
if [ ! -f "$BUILD_SOURCE_PATH/build_opt.h" ]; then
  printf '\n-fmacro-prefix-map="%s"=.' "${BOARD_PLATFORM_PATH//\\/\\\\}" > "$BUILD_PATH/sketch/build.opt"
else
  # Else copy the build_opt.h as build.opt
  # Workaround to the header file preprocessing done by arduino-cli
  # See https://github.com/arduino/arduino-cli/issues/1338
  cp "$BUILD_SOURCE_PATH/build_opt.h" "$BUILD_PATH/sketch/build.opt"
  printf '\n-fmacro-prefix-map="%s"=.' "${BOARD_PLATFORM_PATH//\\/\\\\}" >> "$BUILD_PATH/sketch/build.opt"
fi

# ----------------------------------------------------------------------------
# build_id.h: git build-identity stamp, regenerated on EVERY compile.
#
# Written into the build dir (not the sketch source tree) so it can never go
# stale and wins over any legacy source-dir copy via the same-directory include
# rule. Consumed by sketches/libraries with:  #if __has_include("build_id.h").
# Fail-closed: a dirty tree yields '<sha>-dirty' and no/failed git yields
# 'nogit' -- never a bare clean-looking SHA. Dirty includes a modified core
# submodule (--ignore-submodules=none). Timestamp is the HEAD committer date
# (reproducible), so write-if-changed avoids recompiling the sketch each build.
# Self-contained block (fork delta vs upstream stm32duino).
# ----------------------------------------------------------------------------
BUILD_ID_SRC="$BUILD_SOURCE_PATH"
if git -C "$BUILD_ID_SRC" rev-parse --git-dir >/dev/null 2>&1 \
   && BUILD_GIT_SHA="$(git -C "$BUILD_ID_SRC" rev-parse --short=9 HEAD 2>/dev/null)" \
   && [ -n "$BUILD_GIT_SHA" ]; then
  BUILD_GIT_BRANCH="$(git -C "$BUILD_ID_SRC" rev-parse --abbrev-ref HEAD 2>/dev/null || echo detached)"
  BUILD_UTC_TIME="$(TZ=UTC0 git -C "$BUILD_ID_SRC" log -1 --date=format-local:%Y-%m-%dT%H:%M:%SZ --format=%cd 2>/dev/null || echo nogit)"
  # Dirty = tracked-file edits OR a modified core submodule (--ignore-submodules=none).
  # Untracked files are excluded (--untracked-files=no): they aren't compiled into
  # the binary, and this workspace always carries untracked scratch/plan files; the
  # old diff-index check ignored them too. Without -uno every build would be -dirty.
  if [ -n "$(git -C "$BUILD_ID_SRC" status --porcelain --untracked-files=no --ignore-submodules=none 2>/dev/null)" ]; then
    BUILD_GIT_SHA="${BUILD_GIT_SHA}-dirty"
  fi
else
  BUILD_GIT_SHA="nogit"; BUILD_GIT_BRANCH="nogit"; BUILD_UTC_TIME="nogit"
fi

BUILD_ID_NEW="$(cat <<EOF
// build_id.h - auto-generated by the core prebuild hook on every compile.
// Do not edit or commit; regenerated into the build dir each build.
#ifndef BUILD_ID_H
#define BUILD_ID_H
#define BUILD_GIT_SHA    "${BUILD_GIT_SHA}"
#define BUILD_GIT_BRANCH "${BUILD_GIT_BRANCH}"
#define BUILD_UTC_TIME   "${BUILD_UTC_TIME}"
#endif // BUILD_ID_H
EOF
)"

# write-if-changed: only rewrite when content differs so the including TU
# recompiles only when the stamp actually changes.
BUILD_ID_HDR="$BUILD_PATH/sketch/build_id.h"
if [ ! -f "$BUILD_ID_HDR" ] || [ "$BUILD_ID_NEW" != "$(cat "$BUILD_ID_HDR" 2>/dev/null)" ]; then
  printf '%s\n' "$BUILD_ID_NEW" > "$BUILD_ID_HDR"
fi
