/*
 * HIL_Validation.ino
 *
 * Hardware-in-the-Loop (HIL) RTT Validation Test Suite
 *
 * Comprehensive validation test for STM32 Arduino development using J-Link RTT
 * with deterministic test completion via exit wildcard detection. Designed for
 * automated CI/CD testing and build traceability.
 *
 * Hardware Required:
 * - STM32 board with SWD/JTAG connection
 * - J-Link debugger or ST-Link (reflashed to J-Link firmware)
 *
 * Host Software Required:
 * - J-Link Software Pack
 * - JLinkRTTClient (for HIL/CI testing)
 *
 * Build Integration:
 * When compiled with build scripts (system/ci/build.sh --build-id), includes
 * Git SHA and UTC timestamp for traceability. Gracefully degrades when
 * build_id.h is not available (Arduino IDE compilation).
 *
 * Usage (CI/HIL):
 * 1. Build with traceability: ./system/ci/build.sh libraries/SEGGER_RTT/examples/HIL_Validation --build-id
 * 2. Flash and test: ./system/ci/aflash.sh libraries/SEGGER_RTT/examples/HIL_Validation
 * 3. JLinkRTTClient captures output and detects *STOP* exit wildcard
 *
 * Usage (Arduino IDE):
 * 1. Open: File → Examples → SEGGER_RTT → HIL_Validation
 * 2. Upload to board
 * 3. Connect JLinkRTTClient or JLinkRTTViewer to observe output
 *
 * @author STM32 Arduino HIL Framework
 * @version 1.0
 */

#include <stdio.h>
#include "SEGGER_RTT.h"

// Build identification (auto-generated by scripts when --build-id flag used)
// Gracefully degrades if build_id.h not available (Arduino IDE compilation)
#ifdef __has_include
  #if __has_include("build_id.h")
    #include "build_id.h"
    #define HAS_BUILD_ID
  #endif
#endif

#ifndef HAS_BUILD_ID
  #define BUILD_GIT_SHA "unknown"
  #define BUILD_UTC_TIME "unknown"
#endif

// Test configuration
volatile int test_cycle_count;
const int MAX_TEST_CYCLES = 10;  // Deterministic test completion
const int LED_TOGGLE_INTERVAL_MS = 250;

/**
 * @brief Initialize HIL test environment
 *
 * Sets up RTT communication, GPIO configuration, and emits
 * standardized test header for automated parsing.
 */
void setup() {
    pinMode(LED_BUILTIN, OUTPUT);

    // Initialize RTT for J-Run integration
    SEGGER_RTT_ConfigUpBuffer(0, NULL, NULL, 0, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL);

    // HIL Test Suite Header
    SEGGER_RTT_WriteString(0, "=== STM32 Arduino HIL Validation Suite ===\r\n");
    SEGGER_RTT_printf(0, "Target: %s\r\n", BOARD_NAME);
    SEGGER_RTT_printf(0, "Framework: STM32 Arduino Core\r\n");
    SEGGER_RTT_printf(0, "RTT: SEGGER RTT v8.62\r\n");
    SEGGER_RTT_printf(0, "Build: %s %s\r\n", __DATE__, __TIME__);
    SEGGER_RTT_printf(0, "Git: %s (%s)\r\n", BUILD_GIT_SHA, BUILD_UTC_TIME);
    SEGGER_RTT_WriteString(0, "==========================================\r\n");

    // Enhanced ready token for automated systems with build traceability
    SEGGER_RTT_printf(0, "READY %s %s %s\r\n", BOARD_NAME, BUILD_GIT_SHA, BUILD_UTC_TIME);
    SEGGER_RTT_printf(0, "Test configuration: %d validation cycles\r\n", MAX_TEST_CYCLES);

    test_cycle_count = 0;
}

/**
 * @brief Main HIL validation loop
 *
 * Executes comprehensive hardware validation including:
 * - GPIO functionality (LED toggle)
 * - RTT communication integrity
 * - Printf formatting validation
 * - Deterministic test completion via exit wildcard
 */
void loop() {
    // Hardware validation: GPIO toggle
    digitalWrite(LED_BUILTIN, HIGH);
    delay(LED_TOGGLE_INTERVAL_MS);
    digitalWrite(LED_BUILTIN, LOW);
    delay(LED_TOGGLE_INTERVAL_MS);

    // Increment and report test cycle
    test_cycle_count++;
    SEGGER_RTT_printf(0, "[%05d] HIL Cycle %d/%d - GPIO/RTT validation active\r\n",
                     millis(), test_cycle_count, MAX_TEST_CYCLES);

    // RTT formatting validation (every 3rd cycle)
    if (test_cycle_count % 3 == 0) {
        SEGGER_RTT_printf(0, "  --> Format validation: Hex=0x%04X, Dec=%d, Str=\"%s\"\r\n",
                         test_cycle_count, test_cycle_count, "HIL_PASS");
    }

    // Deterministic test completion check
    if (test_cycle_count >= MAX_TEST_CYCLES) {
        // Emit comprehensive test results
        SEGGER_RTT_WriteString(0, "\r\n=== HIL Validation Results ===\r\n");
        SEGGER_RTT_printf(0, "✓ Completed %d test cycles successfully\r\n", test_cycle_count);
        SEGGER_RTT_printf(0, "✓ GPIO functionality validated (LED toggle)\r\n");
        SEGGER_RTT_printf(0, "✓ RTT communication integrity confirmed\r\n");
        SEGGER_RTT_printf(0, "✓ Printf formatting validation passed\r\n");
        SEGGER_RTT_printf(0, "✓ Deterministic test completion achieved\r\n");
        SEGGER_RTT_WriteString(0, "==============================\r\n");

        // J-Run exit wildcard for deterministic HIL test completion
        SEGGER_RTT_WriteString(0, "*STOP*\r\n");

        // Halt execution with visual indication
        while(1) {
            digitalWrite(LED_BUILTIN, HIGH);
            delay(100);
            digitalWrite(LED_BUILTIN, LOW);
            delay(100);
        }
    }
}
